galaxy_info:
  author: David Cannan
  description: Configuration and management scripts for cdaLab.
  company: Cdaprod
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: EL
      versions:
        - 7
        - 8
    - name: Ubuntu
      versions:
        - xenial
        - bionic
        - focal
  galaxy_tags:
    - network
    - automation
    - pfsense
    - minio
    - kubernetes

dependencies: []